### ISSUE TITLE
plex-media-server with hardened kernel

### ISSUE THREAD

**Issue by propyless** [fearedbliss/bliss-overlay#7]
Hello,

I added your layman overlay for the plex-media-server ebuild. I have been however having issues to get it working.

```
./Plex Media Server: error while loading shared libraries: libgnsdk_dsp.so.3.07.7: cannot enable executable stack as shared object requires: Permission denied
pms # pwd
/var/log/pms
```

There is a apparently a fix for this and was wondering if you want to implement it or if pull requests are allowed. Which is a bit risky seeing as i've never written a ebuild myself.

Here you can find more info on the issue:
https://github.com/devsr/plex-selinux/issues/2
https://wiki.gentoo.org/wiki/Hardened/GNU_stack_quickstart#Compiling_with_--noexecstack
https://forums.plex.tv/discussion/160270/pms-0-9-12-on-selinux

Regards,
Propyless

**Comment by fearedbliss** [comment]
Hey, it seems that this is an issue that needs to be fixed upstream since I have no control over how they compiled their binaries. However, it is suggested from the above links that doing an execstack -c <library> should fix it. Have you tried doing this? If you did, and it worked, I could implement the fix in the next ebuild revision. I'll need to do a quick test to see if clearing this would break a non-hardened environment, but it shouldn't. I don't have a hardened environment to test so as long as you can test the fix and it doesn't break non-hardened systems, it should be fine for me to implement this fix.

**Comment by propyless** [comment]
Okay, I've had some time to try the fix and it does indeed seem to fix the issue.

I needed to install the `sys-devel/prelink` package first and from there I just did `execstack -c /opt/plexmediaserver/libgnsdk_dsp.so.3.07.7`

But maybe theres a way from the ebuild to detect whether a hardened kernel is being used to determine whether the fix should be implemented. For me I think its the pax enabled kernel preventing the lib from loading. I'm not sure if the same issue is present for selinux users though.

**Comment by fearedbliss** [comment]
I have a fix for the ebuild now, but the developers are telling me that the
prelink package is masked in the 'hardened' profile. So I'll need to use
the 'elfix' utility to do it.

**Comment by propyless** [comment]
Oh wow, that was quick! Need me to try it out?
Had no idea I could do it with elfix. I even had it installed! So thanks for that tip =)

**Comment by fearedbliss** [comment]
I didn't know about it either but just learned.. unfortunately after I
installed elfix 0.9.2, I don't see the 'fix-gnustack' package which from
the website it seems like it is the application I need to remove the flag.
I'm researching this atm.

**Comment by propyless** [comment]
```
 * Searching for elfix ...
 * Contents of sys-apps/elfix-0.9.2:
/usr
/usr/sbin
/usr/sbin/migrate-pax
/usr/sbin/paxctl-ng
/usr/sbin/paxmark.sh
/usr/sbin/pypaxctl
/usr/sbin/revdep-pax
/usr/share
/usr/share/doc
/usr/share/doc/elfix-0.9.2
/usr/share/doc/elfix-0.9.2/AUTHORS
/usr/share/doc/elfix-0.9.2/ChangeLog.bz2
/usr/share/doc/elfix-0.9.2/INSTALL.bz2
/usr/share/doc/elfix-0.9.2/README.bz2
/usr/share/doc/elfix-0.9.2/THANKS.bz2
/usr/share/doc/elfix-0.9.2/TODO.bz2
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/paxctl-ng.1.bz2
/usr/share/man/man1/revdep-pax.1.bz2
```

Nothing with fix-gnustack there.. but looking into the elfix repo..
https://gitweb.gentoo.org/proj/elfix.git/tree/misc/fix-gnustack
fix-gnustack exists there at least..

**Comment by fearedbliss** [comment]
Yup it exists in the source file. I'm speaking to blueness atm which is the
elfix developer. He says that 'fix-gnustack' is in the repo but it isn't
installed/included anymore with elfix. He needs to break it out.

**Comment by propyless** [comment]
Ah.. I see. Yeah I read the github info about the /misc later on and saw that it was independant packages.
Alright, well its not a big issue since I already used execstack utility to fix it. but whenever you have something, just give me a message in the issue.

Thanks for your help.

**Comment by fearedbliss** [comment]
Alright I pushed the -r1 for plex. It includes the fix using a new package blueness pushed called 'fix-gnustack'. Please and let me know. Just use the 'hardened' use flag for the package.

**Comment by propyless** [comment]
After updating layman I can't see the -r1

`Available versions:  0.9.15.2^m ~0.9.15.3^m`

**Comment by fearedbliss** [comment]
It's there though as 0.9.15.2-r1 for ~amd64. I tested it before pushing.
There is something wrong on your end..

**Comment by propyless** [comment]
I had a friend grab your overlay and he is also unable to find your r1 ebuild for plex media server

**Comment by fearedbliss** [comment]
It is there:

https://github.com/fearedbliss/bliss-overlay/tree/master/media-tv/plex-media-server

I actually don't use layman, but the new git support in portage. It should
be the same git repo though.

**Comment by akadaedalus** [comment]
I just did a emerge and wondered why fix-gnustack is being pulled (and required unmasking), and found this.  I thought I'd share that I'm using layman-2.3.0 and git to pull the overlay and it has the 0.9.15.2-r1 version.

I can report that on my hardened server this built fine and nothing appears to have blown up when I restarted plex.  

Thanks for maintaining plex in this overlay so I don't have to.  :)

**Comment by fearedbliss** [comment]
Yup. There were some hardened users having issues with Plex crashing
specifically because upstream decided to have a flag set on one of the
libraries. This flag needs to be removed for security reasons and also so
the app doesn't crash. I know you said it didn't crash for you, but it
seems other plex users are being affected.

**Comment by propyless** [comment]
Found it, works now. Thanks for your help @fearedbliss! Much appreciated!

**Comment by fearedbliss** [comment]
Nice to hear! Take care!
