### ISSUE TITLE
Version Bump (Meltdown and Spectre Patches)

### ISSUE THREAD

**Issue by mkocustos** [fearedbliss/bliss-overlay#9]
Please provide new versions that contain the latest bugfixes regarding Meltdown and Spectre:

stable: | 4.14.12
longterm: | 4.9.75

And thank you very much for your work: It is very helpful and very appreciated.

**Comment by fearedbliss** [comment]
Not sure why my email reply didn't post from earlier today but this was the message:

Hey,

Yup this is on my plate of things to do, compiling those kernels as we speak actually. Btw, 4.14 is an LTS kernel as well so you should use that one if needed. I'll compile the kernels for 4.4 and 4.9 as well.

I didn't see the Spectre fixes in the linux kernel's commits, I was looking for the following patch (Unless they committed another solution?):

https://patchwork.kernel.org/patch/10145335/

I believe if those get in, it will be Spectre variant 1 fixes, not variant 2. I'm still trying to learn more about these.

**Comment by fearedbliss** [comment]
I pushed and replaced all of my kernels with latest equivalents.

4.4.39 -> 4.4.110
4.9.60 -> 4.9.75
4.14.10 -> 4.14.12
